### ISSUE TITLE
Please stop sending spam emails

### ISSUE THREAD

**Issue by moggers87** [IPSFoundation/IPS_Whitepaper#1]
I received an email that started off with:

> I have read your code on Github. I think you must be interested in the IPS project.

This is either a lie or you can't read because my Github profile has the following written just above my email address:

> Don't email me if you're a recruiter. Don't email me about your cool new product either.

Do I need to be clearer than that?

**Comment by Nicolasbrock** [comment]
Really sorry to disturb you.
